import { USER_INFO } from "./info";
import { PROJECTS } from "./projects";

export const INFORMATION = {

    PROFILE_PICTURE: USER_INFO.PROFILE_PICTURE,

    NAME: USER_INFO.NAME,
    EMAIL: USER_INFO.EMAIL,
    PHONE: USER_INFO.PHONE,
    BRIEF: USER_INFO.BRIEF,
    RESUME: USER_INFO.RESUME,

    LOCAL_TIME_ZONE: USER_INFO.LOCAL_TIME_ZONE,
    CITY_PICTURE: USER_INFO.CITY_PICTURE,
    CITY: USER_INFO.CITY,
    COUNTRY: USER_INFO.COUNTRY,

    EXPIRIENCE: USER_INFO.EXPIRIENCE,
    TOTAL_PROJECTS: USER_INFO.TOTAL_PROJECTS,

    LINKS: {
        GITHUB: USER_INFO.LINKS.GITHUB,
        TWITTER: USER_INFO.LINKS.TWITTER,
        LINKEDIN: USER_INFO.LINKS.LINKEDIN,
        KODERLABS: USER_INFO.LINKS.KODERLABS,
    },

    SKILLS: USER_INFO.SKILLS,

    PROJECTS,
}
